name: ${COMPOSE_PROJECT_NAME}  #nome prj! (se non lo specifici qua allora si setta come nome folder che contiene questo docker-compose file) quindi ora e.g.i nomi dei containers saranno <project_name>-<service_name>-<index>

services:


  fastapi:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: docker/fastapi-gpu.Dockerfile  #before was docker/fastapi.Dockerfile but prj was all in server1
    #container_name: fastapi  !non specificare il nome, xk tu hai 1 solo server quindi ci sarebbe conflitto nome container e.g.fastapi di dev env -- fastapi staging env. senza sepcificare docker crea automaticamente e.g. <project_name>-<service_name>-<index> cioe <nome_prj>-fastapi-1
    deploy:  #added x server2
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file: .env
    environment:   #!!le vars arrivano all'interno di questo container SOLO PASSANDO attraverso questa door (OPPURE tramite env_file: .env, vedi here qua sopra)!! quindi ovviamente se in .env hai var MYVAR=xxx e poi qua in environment setti MYVAR=yyy allora sarà yyy.
      #REDIS_URL: "redis://redis:6379/0"  #NO, questo hostname "redis" esiste solo dentro il docker engine del server1: fastapi gira sul server2 (altro engine), quindi va sovrascritto con IP+porta pubblicata di server1 qui sotto.
      REDIS_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      REDIS_CACHE_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/1"
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      SQLSERVER_HOST: "${IP_SERVER1}"   #"sqlserver"   x when prj was all in server1
      SQLSERVER_PORT: "1434"   #porta pubblica di sqlserver su server1
      SQLSERVER_DB: "RAGChat"
      QDRANT_URL: "http://${IP_SERVER1}:6339"      #porta pubblica di qdrant su server1
      BASE_URL_OLLAMA: "http://srvai2k22:11434/"   #"http://ollama:11434"
      HF_HOME: "/cache/fastembed/.cache/huggingface"
      FASTEMBED_CACHE_PATH: "/cache/fastembed"   #fastembed (default usa proprio /tmp/fastembed_cache) decide dove settare la sua cache, quindi here re-indirizzo al mio volume target; questo serve quando scarichi manaulmente da riga di comando i 3 models (per averli gia disponibili quando userai l'app). cmnq in config.yam in cache_dir (che utilizzi proprio questa var quando scarichi il modello e.g. vedi embeddings.py) decidi anche li dove download i 3 modelli.
      HOME: "/cache/fastembed"   #da aggiungere xk okey fastembed FASTEMBED_CACHE_PATH per i modelli, ma la sua lib xet scrive i suoi logs in $HOME/.cache/huggingface/xet, quindi $HOME deve esistere.
    # depends_on:  x when prj was all in server1
    #   sqlserver:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    #   qdrant:
    #     condition: service_started
    depends_on: []
    volumes:
      - ./config:/app/config:ro
      - ${DATA_ROOT}/uploads:/app/uploads  #uploads_data:/app/uploads, 
      - ${DATA_ROOT}/fastembed-cache:/cache/fastembed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - rag-network


  celery-worker-high:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: docker/celery-gpu.Dockerfile   #docker/celery.Dockerfile  x when prj was all in server1
    #container_name: celery-worker-high
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      celery -A app.workers.celery_app.celery_app worker
      --queues=high,shared_cleanup
      --concurrency=4
      --prefetch-multiplier=1
      --loglevel=info
      --hostname=worker-high@%h

    env_file: .env
    environment:
      #REDIS_URL: "redis://redis:6379/0"   #x when prj was all in server1
      REDIS_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      REDIS_CACHE_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/1"
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      SQLSERVER_HOST: "${IP_SERVER1}"    #"sqlserver"  x when prj was all in server1
      SQLSERVER_PORT: "1434"   #porta pubblica di sqlserver su server1
      QDRANT_URL: "http://${IP_SERVER1}:6339"   #porta pubblica di qdrant su server1
      HF_HOME: "/cache/fastembed/.cache/huggingface"
      FASTEMBED_CACHE_PATH: "/cache/fastembed"
      HOME: "/cache/fastembed"
    volumes:
      - ${DATA_ROOT}/uploads:/app/uploads  #corretto deve sharing stesso volume anche con fastapi e celery-worker-default   #uploads_data:/app/uploads
      - ${DATA_ROOT}/fastembed-cache:/cache/fastembed
    # depends_on:   x when prj was all in server1
    #   sqlserver:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    depends_on: []
    healthcheck:
      test: ["CMD", "celery", "-A", "app.workers.celery_app.celery_app", "inspect", "ping"] #["CMD", "celery", "-A", "app.workers.celery_app.celery_app", "inspect", "ping", "-d", "worker-high@%h"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rag-network


  celery-worker-default:
    profiles: ["gpu"] 
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    #container_name: celery-worker-default
    restart: unless-stopped
    command: >
      celery -A app.workers.celery_app.celery_app worker
      --queues=default,low
      --concurrency=2
      --prefetch-multiplier=1
      --loglevel=info
      --hostname=worker-default@%h
    env_file: .env
    environment:
      #REDIS_URL: "redis://redis:6379/0"   #x when prj was all in server1
      REDIS_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      REDIS_CACHE_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/1"
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@${IP_SERVER1}:6380/0"
      SQLSERVER_HOST: "${IP_SERVER1}"  #"sqlserver"   x when prj was all in server1
      SQLSERVER_PORT: "1434"   
      QDRANT_URL: "http://${IP_SERVER1}:6339"    
      HF_HOME: "/cache/fastembed/.cache/huggingface"
      FASTEMBED_CACHE_PATH: "/cache/fastembed"
      HOME: "/cache/fastembed"
    volumes:
      - ${DATA_ROOT}/uploads:/app/uploads   #uploads_data:/app/uploads
      - ${DATA_ROOT}/fastembed-cache:/cache/fastembed
    # depends_on:    x when prj was all in server1
    #   sqlserver:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    depends_on: []
    networks:
      - rag-network


  celery-beat:
    profiles: ["infra"]   #infrastructure, quindi server1
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    #container_name: celery-beat
    restart: unless-stopped
    command: >
      celery -A app.workers.celery_app.celery_app beat
      --loglevel=info
      --scheduler redbeat.RedBeatScheduler
    env_file: .env
    environment:
      REDIS_URL: ${REDIS_URL}    #"redis://redis:6379/0"
      HOME: "/cache/fastembed"
      HF_HOME: "/cache/fastembed/.cache/huggingface"
    depends_on:
      - redis
    networks:
      - rag-network


  flower:
    profiles: ["infra"]
    image: mher/flower:2.0
    #container_name: flower
    restart: unless-stopped
    command: >
      celery
      --broker=redis://:${REDIS_PASSWORD}@redis:6379/0
      flower
      --port=5555
      --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5556:5555"  # 5555 x development | 5556 x staging | 5557 x production
    env_file: .env
    depends_on:
      - redis
    networks:
      - rag-network


  qdrant:
    profiles: ["infra"]
    image: qdrant/qdrant:v1.18.2
    #container_name: qdrant
    restart: unless-stopped
    ports:
      - "${IP_SERVER1}:6339:6333"   
      - "${IP_SERVER1}:6335:6334"   #prima "6335:6334"
    volumes:
      - ${DATA_ROOT}/qdrant:/qdrant/storage   #qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__LOG_LEVEL: "INFO"
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/6333"] #["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - rag-network


  redis:
    profiles: ["infra"]
    image: redis:7.0-alpine
    #container_name: redis
    restart: unless-stopped
    ports:
      - "${IP_SERVER1}:6380:6379" # 6379 è per il mio dev, 6380 è per il mio staging, e userò 6381 x il mio prod 
    volumes:
      - ${DATA_ROOT}/redis:/data   #redis_data:/data
    command:
      - redis-server
      - --maxmemory
      - 2gb
      - --maxmemory-policy
      - allkeys-lru
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --requirepass
      - ${REDIS_PASSWORD}
    #"" xk la password contiene una '!' (expansion character x cmd)
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping"]
      #utilizzo di \\ x protezione da ! finale della mia psw su .env
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network


  sqlserver:
    profiles: ["infra"] 
    image: mcr.microsoft.com/mssql/server:2022-latest
    #container_name: sqlserver
    restart: unless-stopped
    ports:
      - "${IP_SERVER1}:1434:1433"     #"1433:1433" avaible solo da chi è gia sul server (non dalla LAN)
    volumes:
      - ${DATA_ROOT}/sqlserver:/var/opt/mssql     #sqlserver_data:/var/opt/mssql 
      - ./docker/sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/sqlserver/entrypoint.sh:/init/entrypoint.sh:ro
    environment:
      SA_PASSWORD: "${SQLSERVER_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "Latin1_General_100_CI_AS_SC_UTF8"
      MSSQL_MEMORY_LIMIT_MB: 2048
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        SQLSERVR_PID=$$!
        trap 'kill -TERM $$SQLSERVR_PID' TERM INT
        bash /init/entrypoint.sh
        wait $$SQLSERVR_PID
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd",
             "-S", "localhost",
             "-U", "SA",
             "-P", "${SQLSERVER_PASSWORD}",
             "-C",
             "-Q", "SET NOCOUNT ON; USE RAGChat; SELECT 1",
             "-b"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - rag-network

#questo non serve piu xk stai usando bind mount verso directory specifiche(decise da TE) del server!
#prima e.g.qdrant_data:/qdrant/storage  salvava i dati persistenti (volumes) dentro  e.g./var/lib/docker/volumes/qdrant_data/_data in maniera gestita da docker
# volumes:
#   qdrant_data:
#     driver: local
#   redis_data:
#     driver: local
#   sqlserver_data:
#     driver: local
#   uploads_data:
#     driver: local

networks:
  rag-network:
    name: ${DOCKER_NETWORK}
    driver: bridge




#ok